const ERROR_CODES = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  USER_DISABLED: 'USER_DISABLED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  NO_ACTIVE_TEAM: 'NO_ACTIVE_TEAM',
  ALREADY_IN_TEAM: 'ALREADY_IN_TEAM',
  INVALID_TEAM_NAME: 'INVALID_TEAM_NAME',
  INVALID_WAREHOUSE_NAME: 'INVALID_WAREHOUSE_NAME',
  INVALID_REQUEST_KEY: 'INVALID_REQUEST_KEY',
  INVALID_INPUT: 'INVALID_INPUT',
  FORBIDDEN: 'FORBIDDEN',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_REVOKED: 'INVITE_REVOKED',
  INVITE_USAGE_EXCEEDED: 'INVITE_USAGE_EXCEEDED',
  INVALID_INVITE_CODE: 'INVALID_INVITE_CODE',
  INVALID_INVITE_EXPIRY: 'INVALID_INVITE_EXPIRY',
  INVALID_MAX_USES: 'INVALID_MAX_USES',
  INVITE_CODE_GENERATION_FAILED: 'INVITE_CODE_GENERATION_FAILED',
  JOIN_REQUEST_NOT_FOUND: 'JOIN_REQUEST_NOT_FOUND',
  JOIN_REQUEST_ALREADY_PENDING: 'JOIN_REQUEST_ALREADY_PENDING',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBERSHIP_NOT_PENDING: 'MEMBERSHIP_NOT_PENDING',
  MEMBERSHIP_NOT_ACTIVE: 'MEMBERSHIP_NOT_ACTIVE',
  INVALID_REVIEW_DECISION: 'INVALID_REVIEW_DECISION',
  INVALID_ROLE: 'INVALID_ROLE',
  CANNOT_CHANGE_OWNER: 'CANNOT_CHANGE_OWNER',
  CANNOT_REMOVE_OWNER: 'CANNOT_REMOVE_OWNER',
  CANNOT_REMOVE_SELF: 'CANNOT_REMOVE_SELF',
  OWNER_CANNOT_LEAVE: 'OWNER_CANNOT_LEAVE',
  TEAM_NOT_ACTIVE: 'TEAM_NOT_ACTIVE',
  WAREHOUSE_NOT_FOUND: 'WAREHOUSE_NOT_FOUND',
  WAREHOUSE_NOT_ACTIVE: 'WAREHOUSE_NOT_ACTIVE',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_NOT_ACTIVE: 'PRODUCT_NOT_ACTIVE',
  PRODUCT_NOT_IN_WAREHOUSE: 'PRODUCT_NOT_IN_WAREHOUSE',
  PRODUCT_VERSION_CONFLICT: 'PRODUCT_VERSION_CONFLICT',
  PRODUCT_HAS_STOCK: 'PRODUCT_HAS_STOCK',
  PRODUCT_ALREADY_REMOVED: 'PRODUCT_ALREADY_REMOVED',
  PRODUCT_ALREADY_DELETED: 'PRODUCT_ALREADY_DELETED',
  PRODUCT_ALREADY_ACTIVE: 'PRODUCT_ALREADY_ACTIVE',
  PRODUCT_STILL_IN_WAREHOUSE: 'PRODUCT_STILL_IN_WAREHOUSE',
  PRODUCT_WAREHOUSE_STATE_CONFLICT: 'PRODUCT_WAREHOUSE_STATE_CONFLICT',
  PRODUCT_CATALOG_DELETED: 'PRODUCT_CATALOG_DELETED',
  INVALID_PRODUCT_VERSION: 'INVALID_PRODUCT_VERSION',
  INVALID_DELETE_REASON: 'INVALID_DELETE_REASON',
  INVALID_PRODUCT_NAME: 'INVALID_PRODUCT_NAME',
  INVALID_PRODUCT_CODE: 'INVALID_PRODUCT_CODE',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  INVALID_UNIT: 'INVALID_UNIT',
  INVALID_BRAND: 'INVALID_BRAND',
  INVALID_SPECIFICATION: 'INVALID_SPECIFICATION',
  INVALID_DESCRIPTION: 'INVALID_DESCRIPTION',
  INVALID_COVER: 'INVALID_COVER',
  INVALID_STOCK_QUANTITY: 'INVALID_STOCK_QUANTITY',
  INVALID_MIN_STOCK: 'INVALID_MIN_STOCK',
  PRODUCT_LIMIT_REACHED: 'PRODUCT_LIMIT_REACHED',
  INVALID_CURSOR: 'INVALID_CURSOR',
  INVALID_PAGE_SIZE: 'INVALID_PAGE_SIZE',
  REQUEST_KEY_CONFLICT: 'REQUEST_KEY_CONFLICT',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  DATABASE_ERROR: 'DATABASE_ERROR',
  UNKNOWN_ACTION: 'UNKNOWN_ACTION',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
};

class ApiError extends Error {
  constructor(code, message) {
    super(message);
    this.name = 'ApiError';
    this.code = code;
  }
}

function isApiError(error) {
  return Boolean(
    error && (
      error instanceof ApiError ||
      Object.keys(ERROR_CODES).some((key) => ERROR_CODES[key] === error.code)
    )
  );
}

module.exports = {
  ApiError,
  ERROR_CODES,
  isApiError
};
