const ERROR_CODES = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  USER_DISABLED: 'USER_DISABLED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  NO_ACTIVE_TEAM: 'NO_ACTIVE_TEAM',
  ALREADY_IN_TEAM: 'ALREADY_IN_TEAM',
  INVALID_TEAM_NAME: 'INVALID_TEAM_NAME',
  INVALID_WAREHOUSE_NAME: 'INVALID_WAREHOUSE_NAME',
  INVALID_REQUEST_KEY: 'INVALID_REQUEST_KEY',
  MEMBERSHIP_NOT_ACTIVE: 'MEMBERSHIP_NOT_ACTIVE',
  TEAM_NOT_ACTIVE: 'TEAM_NOT_ACTIVE',
  WAREHOUSE_NOT_FOUND: 'WAREHOUSE_NOT_FOUND',
  DUPLICATE_REQUEST: 'DUPLICATE_REQUEST',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNKNOWN_ACTION: 'UNKNOWN_ACTION',
  CLOUD_ENV_NOT_CONFIGURED: 'CLOUD_ENV_NOT_CONFIGURED',
  CLOUD_NOT_AVAILABLE: 'CLOUD_NOT_AVAILABLE',
  CLOUD_CALL_FAILED: 'CLOUD_CALL_FAILED',
  BUSINESS_ERROR: 'BUSINESS_ERROR',
  BOOTSTRAP_FAILED: 'BOOTSTRAP_FAILED'
};

const ERROR_MESSAGES = {
  [ERROR_CODES.UNAUTHENTICATED]: '无法确认当前微信身份，请重新进入小程序。',
  [ERROR_CODES.USER_DISABLED]: '当前账号已停用，请联系管理员。',
  [ERROR_CODES.USER_NOT_FOUND]: '用户尚未完成初始化，请重试。',
  [ERROR_CODES.NO_ACTIVE_TEAM]: '当前尚未加入有效团队。',
  [ERROR_CODES.ALREADY_IN_TEAM]: '你已经加入团队，正在刷新团队信息。',
  [ERROR_CODES.INVALID_TEAM_NAME]: '团队名称需为2至30个字符。',
  [ERROR_CODES.INVALID_WAREHOUSE_NAME]: '默认仓库名称需为1至30个字符。',
  [ERROR_CODES.INVALID_REQUEST_KEY]: '提交状态已失效，请重新操作。',
  [ERROR_CODES.MEMBERSHIP_NOT_ACTIVE]: '当前团队成员关系无效。',
  [ERROR_CODES.TEAM_NOT_ACTIVE]: '当前团队不可用。',
  [ERROR_CODES.WAREHOUSE_NOT_FOUND]: '默认仓库不存在，请联系管理员。',
  [ERROR_CODES.DUPLICATE_REQUEST]: '该创建请求已处理，请刷新后重试。',
  [ERROR_CODES.DATABASE_ERROR]: '云端数据处理失败，请稍后重试。',
  [ERROR_CODES.INTERNAL_ERROR]: '云服务处理异常，请稍后重试。',
  [ERROR_CODES.UNKNOWN_ACTION]: '当前功能暂不可用。',
  [ERROR_CODES.CLOUD_ENV_NOT_CONFIGURED]: '仓库管理器云环境尚未配置。',
  [ERROR_CODES.CLOUD_NOT_AVAILABLE]: '当前运行环境暂不支持云开发。',
  [ERROR_CODES.CLOUD_CALL_FAILED]: '云服务暂时不可用，请稍后重试。',
  [ERROR_CODES.BUSINESS_ERROR]: '请求处理失败，请稍后重试。',
  [ERROR_CODES.BOOTSTRAP_FAILED]: '应用初始化失败，请重新加载。'
};

module.exports = {
  ERROR_CODES,
  ERROR_MESSAGES
};
