const ERROR_CODES = {
  CLOUD_NOT_AVAILABLE: 'CLOUD_NOT_AVAILABLE',
  CLOUD_CALL_FAILED: 'CLOUD_CALL_FAILED',
  BUSINESS_ERROR: 'BUSINESS_ERROR',
  BOOTSTRAP_FAILED: 'BOOTSTRAP_FAILED'
};

const ERROR_MESSAGES = {
  [ERROR_CODES.CLOUD_NOT_AVAILABLE]: '当前运行环境暂不支持云开发。',
  [ERROR_CODES.CLOUD_CALL_FAILED]: '云服务暂时不可用，请稍后重试。',
  [ERROR_CODES.BUSINESS_ERROR]: '请求处理失败，请稍后重试。',
  [ERROR_CODES.BOOTSTRAP_FAILED]: '应用初始化失败，请重新加载。'
};

module.exports = {
  ERROR_CODES,
  ERROR_MESSAGES
};
